#ifndef XQC_WEBTRANSPORT_VERSION_TEST_H
#define XQC_WEBTRANSPORT_VERSION_TEST_H
void xqc_test_wt_version_negotiation(void);
void xqc_test_wt_version_fallback(void);
void xqc_test_wt_version_prerequisites(void);
void xqc_test_wt_version_settings_errors(void);
void xqc_test_wt_version_advertisement(void);
void xqc_test_wt_version_connect_tokens(void);
void xqc_test_wt_client_session_response(void);
void xqc_test_wt_client_session_rejected(void);
void xqc_test_wt_draft16_close_utf8(void);
void xqc_test_wt_draft16_close_utf8_errors(void);
void xqc_test_wt_draft16_drain_streams(void);
void xqc_test_wt_draft16_session_limit(void);
void xqc_test_wt_draft16_pooled_sessions(void);
void xqc_test_wt_draft16_pooling_requires_flow_control(void);
void xqc_test_wt_draft16_flow_capsules(void);
void xqc_test_wt_draft16_credit_renewal(void);
void xqc_test_wt_application_protocol(void);
void xqc_test_wt_application_protocol_errors(void);
void xqc_test_wt_application_protocol_inputs(void);
#endif
