from pyxquic_wt._session import WebTransportSession

class WebTransportConnection:
    @property
    def is_connected(self) -> bool: ...
    @property
    def srtt_us(self) -> int: ...
    @property
    def srtt_ms(self) -> float: ...
    @property
    def send_count(self) -> int: ...
    @property
    def recv_count(self) -> int: ...
    @property
    def session_count(self) -> int: ...

    async def open_session(self, path: str) -> WebTransportSession: ...
    async def close(self) -> None: ...
