class WebTransportError(Exception): ...

class QuicConnectionError(WebTransportError): ...

class SessionClosedError(WebTransportError):
    error_code: int
    reason: str
    def __init__(self, error_code: int = 0, reason: str = "") -> None: ...

class StreamResetError(WebTransportError):
    error_code: int
    def __init__(self, error_code: int = 0) -> None: ...

class StreamStopError(WebTransportError):
    error_code: int
    def __init__(self, error_code: int = 0) -> None: ...

class HandshakeError(WebTransportError): ...

class SessionRejectedError(WebTransportError):
    status_code: int
    def __init__(self, status_code: int = 0) -> None: ...
