from typing import AsyncIterator

from pyxquic_wt._stream import BidiStream, SendStream, ReceiveStream

class WebTransportSession:
    @property
    def session_id(self) -> int: ...
    @property
    def is_closed(self) -> bool: ...

    async def send_bidi(self, data: bytes, fin: bool = True) -> int: ...
    async def recv(self, timeout: float = ...) -> bytes: ...
    async def create_bidirectional_stream(self) -> BidiStream: ...
    async def incoming_bidirectional_streams(self) -> AsyncIterator[BidiStream]: ...

    async def send_uni(self, data: bytes) -> int: ...
    async def recv_uni(self, timeout: float = ...) -> bytes: ...
    async def create_unidirectional_stream(self) -> SendStream: ...
    async def incoming_unidirectional_streams(self) -> AsyncIterator[ReceiveStream]: ...

    async def send_datagram(self, data: bytes) -> int: ...
    async def recv_datagram(self, timeout: float = ...) -> bytes: ...

    async def close(self, error_code: int = 0, reason: str = "") -> None: ...
