import asyncio
from typing import AsyncIterator

class BidiStream:
    stream_id: int

    def __init__(self, connection: object, stream_id: int) -> None: ...
    async def read(self, max_bytes: int = -1, timeout: float = ...) -> bytes: ...
    async def read_all(self, timeout: float = ...) -> bytes: ...
    async def recv(self, timeout: float = ...) -> bytes: ...
    async def write_all(self, data: bytes, end_stream: bool = False) -> int: ...
    def reset(self, error_code: int = 0) -> None: ...
    def stop_sending(self, error_code: int = 0) -> None: ...
    async def __aenter__(self) -> "BidiStream": ...
    async def __aexit__(self, exc_type: object, exc_val: object, exc_tb: object) -> None: ...
    def __aiter__(self) -> "BidiStream": ...
    async def __anext__(self) -> bytes: ...

class SendStream:
    stream_id: int

    def __init__(self, connection: object, stream_id: int) -> None: ...
    async def write(self, data: bytes, end_stream: bool = False) -> int: ...
    async def close(self) -> None: ...

class ReceiveStream:
    stream_id: int

    def __init__(self, connection: object, stream_id: int) -> None: ...
    async def read(self, max_bytes: int = -1, timeout: float = ...) -> bytes: ...
    async def read_all(self, timeout: float = ...) -> bytes: ...
    async def recv(self, timeout: float = ...) -> bytes: ...
    async def __aenter__(self) -> "ReceiveStream": ...
    async def __aexit__(self, exc_type: object, exc_val: object, exc_tb: object) -> None: ...
    def __aiter__(self) -> "ReceiveStream": ...
    async def __anext__(self) -> bytes: ...
