name: Build interop Docker image

on:
  push:
    branches: [ main, interop ]

permissions: read-all

jobs:
  build:
    if: github.repository == 'alibaba/xquic'
    permissions:
      packages: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and publish interop docker image
      uses: docker/build-push-action@v4
      with:
        context: interop
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/xquic-interop:latest

    - name: Push image to GHCR
      run: |
        docker buildx imagetools create \
          --tag ghcr.io/${{ github.repository }}/xquic-interop:latest \
          ${{ secrets.DOCKERHUB_USERNAME }}/xquic-interop:latest